# Generated by Django 5.0.7 on 2024-07-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=34)),
                ('object_naming_result', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
